### ISSUE TITLE
[Bug] Date Field has disappeared after select date in Chrome Version 74

### ISSUE THREAD

**Issue by N00D13** [Orckestra/C1-CMS-Foundation#666] opened 2019-05-06 11:36 UTC
**Prerequisites:**
- Default C1 installation (tested with v6.6.6912.30810)
- A data type with a date field
- Chrome Version 74.0.3729.131 (Official Build) (64-bit)

If you use the date selector to select a date, the field disappears. 
This only happens in the new Chrome version. It still works in the 73.

**Screenshots:**
_Correct looking form before select date_
![no-error](https://user-images.githubusercontent.com/1469954/57222641-9d6eae00-7003-11e9-8eb0-e397adc0deaf.png)

_Broken form markup after select date_
![error](https://user-images.githubusercontent.com/1469954/57222660-b0817e00-7003-11e9-87d3-b595bfa84838.png)

**Comment by N00D13** [comment] 2019-05-07 12:45
Also tested in C1 v4.2 and v4.3.
Same problem! In Chrome version 73 everything is okay and in version 74 the Date Field disappears.

**Comment by mawtex** [comment] 2019-05-07 13:28
@N00D13 we can reproduce this and will look into it. 

For those looking for a workaround to this issue: Use Firefox.

**Comment by aeont** [comment] 2019-05-12 22:43
few colleagues of mine reported the same: Chrome: 74.0.3729.131 64-bit. 
C1 CMS: 6.5
Workaround found: IE

**Comment by wwwysocki** [comment] 2019-05-13 10:38
The fix has been validated

**Closed** 2019-05-13 13:38 UTC
Labels: QA Verified, bug, severity:high

**Comment by mawtex** [comment] 2019-05-16 12:59
Fix is online as a package for C1 CMS versions 6.5 and 6.6 - to install: On the System perspective, open "Packages | Available Packages | C1.Updates" and install the package C1.Updates.ChromeDateFieldFix.

**Comment by mawtex** [comment] 2019-05-21 13:02
For general information: the fix also resolves the following issue: 

In Chrome 74, editing a form (using the Form Builder package) you get a blank tab on "Submit Actions" and you cannot edit/save forms. 

After installing C1.Updates.ChromeDateFieldFix this issue goes away.

**Comment by burningice2866** [comment] 2019-05-28 13:14
When can we expect to see an official 6.6.1 release with bugfixes since the 6.6 release.

The proposed fix doesn't scale and maintaining a custom unofficial version internally for automated deployment was something we had hoped was of the past.

**Comment by djalfe** [comment] 2019-05-31 11:10
> Fix is online as a package for C1 CMS versions 6.5 and 6.6 - to install: On the System perspective, open "Packages | Available Packages | C1.Updates" and install the package C1.Updates.ChromeDateFieldFix.

I have the same problem in build no. 6.1.6325.31805, but C1.Updates.ChromeDateFieldFix is not in the list of "available packages".
