### ISSUE TITLE
[ActiveDirectory][Upgrade] Functions not render in edit mode.

### ISSUE THREAD

**Issue by ThisIsMeJKB** [Orckestra/C1-CMS-Foundation#500] opened 2017-11-20 19:24 UTC
I'm noticing some weird behavior (just noticed this recently).

I just upgraded a site from v4.3 to v6.2 and now when I go to edit a page with a custom Function the rendered version of the function doesn't ever load in the editor. I just continue to get the spinning green circle.  BUT when you look at the published page no the public side of the website (or go into "Preview" tab in the editor) the page renders completely, without issue.

Here is the error that gets generated inside the Server Log:

**Failed to build preview for page template '0526ad34-c540-418e-8c23-0eec2a8da2ce'. Reason: Error; Output:
Opening url: http://[hostname]//Renderers/TemplatePreview.ashx?p=e3c00770-2127-4da9-95cb-a8660f7b5ad6&t=0526ad34-c540-418e-8c23-0eec2a8da2ce&hash=1482161078
page.onResourceError: url 'http://[hostname]//Renderers/TemplatePreview.ashx?p=e3c00770-2127-4da9-95cb-a8660f7b5ad6&t=0526ad34-c540-418e-8c23-0eec2a8da2ce&hash=1482161078'; Error code: 204. Description: Host requires authentication
ERROR: preview.js script is not present in the response body
END_OF_REPLY**

This wasn't always happening, when I first did the upgrade last week these functions were loading with no problem. This seems to only happen on pages that reference custom functions I have created. Other pages are editable with no problem.

Any thoughts?

**Comment by ThisIsMeJKB** [comment] 2017-11-20 19:59
Some more info.

I'm using the **ActiveDirectory add-on** on this site.

It looks like the very first line inside the **TemplatePreview.ashx** is failing, where it executes **!UserValidationFacade.IsLoggedIn()**. Apparently, i'm not recognized as being logged in although I've used Windows Auth to get myself into the C1 CMS admin.

**Comment by napernik** [comment] 2017-12-06 15:44
Hi @ThisIsMeJKB 

Which version of the Active Directory add-on are you using? I checked the commit history, and it looks like something I might have already fixed in the latest 1.1.0 version (available for C1 5.0 or newer). Uninstalling and reinstalling the Active Directory package should solve the problem.

If you have problems with the packages that are a part of paid subscriptions, do not hesitate to contact us via c1support(at)orckestra.com to get a much quicker response.

**Comment by ThisIsMeJKB** [comment] 2017-12-07 11:10
Ok, thanks @napernik.

I'm not sure specifically of the version of the plug-in being used, it was purchased 4-5 years ago and used for v4.3 so it doesn't contain any of the updates/fixes for v5.0.

This client doesn't have a paid subscription as this plug-in was a standalone purchase, does that still entitle them to some level of commercial support?

I will attempt to uninstall/reinstall the plug-in at some point today and let you know what that does for me. I assumed I would not be able to upgrade it since there wasn't a paid subscription in place.

**Comment by napernik** [comment] 2017-12-07 13:18
> I assumed I would not be able to upgrade it since there wasn't a paid subscription in place.
The latest versions should still accept previously purchased permanent license file.

Without a subscription we will not address bugs in the old versions of the packages, but will look into critical bugs in the latest versions of the commercial packages that are reproducible in the latest release of C1.

**Closed** 2017-12-07 13:18 UTC
Labels: bug
