### ISSUE TITLE
Customizing SEO XML Sitemap

### ISSUE THREAD

**Issue by bhargavjoshi20** [Orckestra/C1-CMS-Foundation#474] opened 2017-08-28 08:06 UTC
Hi,

My company uses the Venus system built on Composite C1 CMS.

Our CMS generates the SEO XML Sitemap located at: https://DOMAIN_NAME/sitemap.xml

We want to customize it further. For example: Editing lastmod date, changefreq, priority and exclude certain directories, but I am not able to find any documentation or add-on for that. 

This URL: https://docs.c1.orckestra.com/Configuration/Generating-Sitemaps suggests that CMS creates sitemap itself, but there isn't any information of customizing it.

Could anyone help me for that?

-
Regards,
Joshi

**Comment by burningice2866** [comment] 2017-08-28 10:04
Related to this which could cover a chance to modify each node before its outputted in the sitemap.

https://github.com/Orckestra/C1-CMS-Foundation/issues/456

**Comment by bhargavjoshi20** [comment] 2017-08-29 13:52
Hi,

To be honest, I didn't understood this.

Actually, there is a hierarchy of webpages in our marketplace; we have over 200,000 pages and mainly they are organized in 4 levels of hierarchy. 

Now, the system by default creates the sitemap; but we want to customize it as explained above.

So I am looking for any add-ons or settings so I could define these rules.

**Comment by burningice2866** [comment] 2017-08-29 13:56
If you we're provided a method/event that allowed you to modify ie.  lastmod date, changefreq and priority for each element in sitemap.xml, wouldn't that solve your needs?

**Comment by bhargavjoshi20** [comment] 2017-08-29 14:23
Yes, that is what I am looking for. 
Could you tell me how can I do that?

**Comment by burningice2866** [comment] 2017-08-29 14:32
You cannot at the moment, but go and vote for https://github.com/Orckestra/C1-CMS-Foundation/issues/456 to show your interest and then its more likely such a feature can be made.

**Comment by bhargavjoshi20** [comment] 2017-08-29 14:35
Okay. I understood. Let me vote there. 
Hope this feature will be available soon.

**Comment by mawtex** [comment] 2017-08-30 15:29
I guess this can now be called a duplicate of #456 so I will close this. 

For getting the feature request in #456 to happen, just a general reminder: sending us a "focused" pull request is always the fastest way, if you want to see a new feature in C1 CMS (in most open source projects, I guess). You upvoting on issues do help us pick the most community relevant tasks for situations where developers in the C1 CMS core group are not busy with other tasks, but those situations can be far apart.

**Closed by mawtex** 2017-08-30 15:29 UTC

**Comment by bhargavjoshi20** [comment] 2017-08-30 15:41
Hi @mawtex and @burningice2866 

Actually I am in a little bit hurry in creating customized XML sitemap, so it won't be possible to wait till  you include the new feature. 

Is it possible if I hire a .Net developer and he can create some functionality for generating the dynamic XML sitemap? If yes, then could you guide me a little bit?

**Comment by burningice2866** [comment] 2017-08-30 15:50
@bhargavjoshi20 you can write me at *pauli [at] burningice.dk [dot] dk* and we can figure something out.

**Comment by mawtex** [comment] 2017-08-30 15:51
In web.config locate this:

<add name="SiteMap" verb="GET" path="sitemap.xml" type="Composite.AspNet.SiteMapHandler, Composite" />

That is the current handler, code is here:

https://github.com/Orckestra/C1-CMS-Foundation/blob/master/Composite/AspNet/SiteMapHandler.cs

Change the type to your own handler - you can use our handler code as a starting point.

**Comment by bhargavjoshi20** [comment] 2017-08-31 02:40
Hi @burningice2866 and @mawtex 
Many thanks for your input. 
I will discuss with my IT team about this and figure out how can we customize it and @burningice2866 I will write you an email as well.
