### ISSUE TITLE
when linking on events, links to dedicated events get broken after some time and need a server restart from c1 backend

### ISSUE THREAD

**Issue by mmillendorfer** [Orckestra/C1-CMS-Foundation#621] opened 2018-09-16 06:35 UTC
Hi,

I'm linking from the main page to an event from event calender plugin, which works fine direct after setting the link in CMS. Some hous later I only see the not-translated "~/event(5c1460b0-6892-4262-91bf-7f2822d81e03)" part. To resove the issue the server needs to be restarted  within the C1 console.

After a couple of hours another restart is necessary. 

the error log is empty.

any hint is welcome,
thanks a lot
cheers
Markus

**Comment by DBailey635** [comment] 2018-09-16 16:35
This may be a duplicate of issue #339.

**Comment by mawtex** [comment] 2018-09-17 12:50
@mmillendorfer what version of C1 are you using?

**Comment by mmillendorfer** [comment] 2018-09-19 07:58
@mawtex 
I'm using C1 CMS 6.5

@DBailey635 
it describes a similar issue

cheers
Markus

**Comment by napernik** [comment] 2018-10-18 14:29
A newer version of the event calendar doesn't have this problem. 
Though the link format is a bit different:
<a href="~/calendarEvent(bccb5f74-d48f-498b-8cd2-0e3268d1fa8b)">...</a>

The underlying issue seem to be the same as @DBailey635 describes

**Closed** 2018-12-04 13:49 UTC
Labels: bug, severity:high
